[package]
name = "boost/callable_traits"
version = "2.3.2"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
license = "BSL-1.0"
repository = "https://github.com/boostorg/callable_traits/tree/2.3.2"
documentation = "http://boost.org/libs/callable_traits"
readme = "README.md"
description = """
modern C++ type traits and metafunctions for callable types
"""
