[package]
name = "boost/align"
version = "1.65.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/align"
documentation = "http://boost.org/libs/align"
readme = "README.md"
description = """
Boost.Align
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/static_assert" = "1.63.0"
"boost/throw_exception" = "1.63.0"
