[package]
name = "boost/logic"
version = "1.63.0"
edition = "2011"
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
license = "BSL-1.0"
repository = "https://github.com/boostorg/logic/tree/boost-1.63.0"
documentation = "http://boost.org/libs/logic"
readme = "README.md"
description = """
Boost.org logic module
"""

[dependencies]
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
