[package]
name = "boost/tuple"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/tuple/tree/boost-1.66.0"
documentation = "http://boost.org/libs/tuple"
description = """
Boost.org tuple module
"""

[dependencies]
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/static_assert" = "1.63.0"
"boost/type_traits" = "1.65.0"
