[package]
name = "boost/move"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+matken11235@users.noreply.github.com>"]
license = "BSL-1.0"
repository = "https://github.com/boostorg/move"
documentation = "http://boost.org/libs/move"
readme = "README.md"
description = """
Boost.org move module
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/static_assert" = "1.63.0"
