[package]
name = "boost/typeof"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/typeof"
documentation = "http://boost.org/libs/typeof"
description = """
Boost.org typeof module
"""

[dependencies]
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/mpl" = "1.66.0"
"boost/preprocessor" = "1.66.0"
"boost/type_traits" = "1.65.0"
