[package]
name = "boost/atomic"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/atomic/tree/boost-1.66.0"
documentation = "http://boost.org/libs/atomic"
readme = "README.md"
description = """
Boost.Atomic
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/type_traits" = "1.65.0"

[build]
system = "poac"
lib = true
