[package]
name = "boost/crc"
version = "1.56.0"
cpp = 11
authors = ["Ken Matsui <26405363+matken11235@users.noreply.github.com>"]
repository = "https://github.com/boostorg/crc"
documentation = "http://boost.org/libs/crc"
description = """
Boost.org crc module
"""

[dependencies]
"boost/config" = "1.66.0"
"boost/integer" = "1.65.0"
