[package]
name = "boost/compatibility"
version = "1.58.0"
edition = "2011"
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/compatibility/tree/boost-1.58.0"
documentation = "http://boost.org/libs/compatibility"
description = """
Boost.org compatibility module
"""
