[package]
name = "boost/compatibility"
version = "1.58.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/compatibility"
documentation = "http://boost.org/libs/compatibility"
description = """
Boost.org compatibility module
"""
