[package]
name = "boost/compatibility"
version = "1.58.0"
cpp = 11
authors = ["Beman Dawes <bdawes@acm.org>",
           "Daniel James <daniel@calamity.org.uk>",
           "Ralf W. Grosse-Kunstleve <rwgk@yahoo.com>",
           "Michael A. Jackson <mike.jackson@bluequartz.net>",
           "Troy D. Straszheim <troy@resophonic.com>",
           "Peter Dimov <pdimov@pdimov.com>",
           "Jens Maurer <jens.maurer@gmx.net>",
           "Andreas Huber <ahd6974-boostorg@live.com>",
           "Douglas Gregor <doug.gregor@gmail.com>",
           "Aleksey Gurtovoy <agurtovoy@meta-comm.com>",
           "John Maddock <john@johnmaddock.co.uk>"]
repository = "https://github.com/boostorg/compatibility"
documentation = "http://boost.org/libs/compatibility"
description = """
Boost.org compatibility module
"""
