[package]
name = "boost/vmd"
version = "1.66.0"
edition = "2011"
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/vmd/tree/boost-1.66.0"
documentation = "http://boost.org/libs/vmd"
description = """
Boost.org VMD module
"""

[dependencies]
"boost/preprocessor" = "1.66.0"
