[package]
name = "boost/core"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+matken11235@users.noreply.github.com>"]
repository = "https://github.com/boostorg/core"
documentation = "http://boost.org/libs/core"
readme = "README.md"
description = """
Boost Core Utilities
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
