[package]
name = "boost/integer"
version = "1.65.0"
cpp = 11
authors = ["Ken Matsui <26405363+matken11235@users.noreply.github.com>"]
repository = "https://github.com/boostorg/integer"
documentation = "http://boost.org/libs/integer"
readme = "README.md"
description = """
Boost.org integer module
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/static_assert" = "1.63.0"
