[package]
name = "boost/integer"
version = "1.65.0"
edition = "2011"
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/integer/tree/boost-1.65.0"
documentation = "http://boost.org/libs/integer"
readme = "README.md"
description = """
Boost.org integer module
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/static_assert" = "1.63.0"
