[package]
name = "boost/static_assert"
version = "1.63.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/static_assert/tree/boost-1.63.0"
documentation = "http://boost.org/libs/static_assert"
readme = "README.md"
description = """
Boost.org static_assert module
"""

[dependencies]
"boost/config" = "1.66.0"
