[package]
name = "boost/smart_ptr"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/smart_ptr"
documentation = "http://boost.org/libs/smart_ptr"
readme = "README.md"
description = """
Boost.IO
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/move" = "1.66.0"
"boost/predef" = "1.66.0"
"boost/static_assert = "1.63.0"
"boost/throw_exception" = "1.63.0"
"boost/type_traits" = "1.65.0"
