[package]
name = "boost/functional"
version = "1.66.0"
edition = "2011"
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/functional/tree/boost-1.66.0"
documentation = "http://boost.org/libs/functional"
description = """
Boost.org functional module
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/detail" = "1.66.0"
"boost/function" = "1.66.0"
"boost/function_types" = "1.66.0"
"boost/integer" = "1.65.0"
"boost/iterator" = "1.66.0"
"boost/mpl" = "1.66.0"
"boost/optional" = "1.66.0"
"boost/preprocessor" = "1.66.0"
"boost/static_assert" = "1.63.0"
"boost/type_traits" = "1.65.0"
"boost/typeof" = "1.66.0"
"boost/utility" = "1.66.0"
