[package]
name = "boost/assert"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/assert/tree/boost-1.66.0"
documentation = "http://boost.org/libs/assert"
readme = "README.md"
description = """
Boost.Assert
"""

[dependencies]
"boost/config" = "1.66.0"
