[package]
name = "boost/iterator"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/iterator"
documentation = "http://boost.org/libs/iterator"
description = """
Boost.org iterator module
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/concept_check" = "1.64.0"
"boost/config" = "1.66.0"
"boost/conversion" = "1.65.0"
"boost/core" = "1.66.0"
"boost/detail" = "1.66.0"
"boost/function_types" = "1.66.0"
"boost/fusion" = "1.66.0"
"boost/mpl" = "1.66.0"
"boost/optional" = "1.66.0"
"boost/smart_ptr" = "1.66.0"
"boost/static_assert" = "1.63.0"
"boost/type_traits" = "1.65.0"
"boost/utility" = "1.66.0"
