[package]
name = "boost/array"
version = "1.64.0"
edition = "2011"
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/array/tree/boost-1.64.0"
documentation = "http://boost.org/libs/array"
description = """
Boost.org array module
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/static_assert" = "1.63.0"
"boost/throw_exception" = "1.63.0"
