[package]
name = "boost/type_index"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+matken11235@users.noreply.github.com>"]
repository = "https://github.com/boostorg/type_index"
documentation = "http://boost.org/libs/type_index"
readme = "README.md"
description = """
Runtime/Compile time copyable type info.
"""

[dependencies]
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/functional" = "1.66.0"
"boost/mpl" = "1.66.0"
"boost/preprocessor" = "1.66.0"
"boost/smart_ptr" = "1.66.0"
"boost/static_assert" = "1.63.0"
"boost/throw_exception" = "1.63.0"
"boost/type_traits" = "1.65.0"
