[package]
name = "boost/optional"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/optional"
documentation = "http://boost.org/libs/optional"
readme = "README.md"
description = """
Boost.org optional module
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/detail" = "1.66.0"
"boost/move" = "1.66.0"
"boost/mpl" = "1.66.0"
"boost/static_assert" = "1.63.0"
"boost/throw_exception" = "1.63.0"
"boost/type_traits" = "1.65.0"
"boost/utility" = "1.66.0"
