[package]
name = "boost/bind"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/bind"
documentation = "http://boost.org/libs/bind"
readme = "README.md"
description = """
Boost.org bind module
"""

[dependencies]
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
