[package]
name = "boost/config"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/config/tree/boost-1.66.0"
documentation = "http://boost.org/libs/config"
readme = "README.md"
description = """
Boost.org config module
"""
