[package]
name = "boost/preprocessor"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/preprocessor/tree/boost-1.66.0"
documentation = "http://boost.org/libs/preprocessor"
description = """
Boost.org preprocessor module
"""
