[package]
name = "boost/mp11"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/mp11/tree/boost-1.66.0"
documentation = "http://boost.org/libs/mp11"
readme = "README.md"
description = """
C++11 metaprogramming library
"""

[dependencies]
"boost/config" = "1.66.0"
