[package]
name = "boost/winapi"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/winapi"
documentation = "http://boost.org/libs/winapi"
readme = "README.md"
description = """
Windows API declarations without <windows.h>, for internal Boost use.
"""

[dependencies]
"boost/config" = "1.66.0"
"boost/predef" = "1.66.0"
