[package]
name = "boost/io"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/io"
documentation = "http://boost.org/libs/io"
readme = "README.md"
description = """
Boost.IO
"""

[dependencies]
"boost/config" = "1.66.0"
