[package]
name = "boost/function"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+matken11235@users.noreply.github.com>"]
repository = "https://github.com/boostorg/function"
documentation = "http://boost.org/libs/function"
readme = "README.md"
description = """
Boost.org function module
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/bind" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/integer" = "1.65.0"
"boost/move" = "1.66.0"
"boost/mpl" = "1.66.0"
"boost/preprocessor" = "1.66.0"
"boost/throw_exception" = "1.63.0"
"boost/type_index" = "1.66.0"
"boost/type_traits" = "1.65.0"
"boost/typeof" = "1.66.0"
