[package]
name = "boost/system"
version = "1.66.0"
cpp = 11
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
repository = "https://github.com/boostorg/system/tree/boost-1.66.0"
documentation = "http://boost.org/libs/system"
description = """
Boost.org system module
"""

[dependencies]
"boost/assert" = "1.66.0"
"boost/config" = "1.66.0"
"boost/core" = "1.66.0"
"boost/predef" = "1.66.0"
"boost/winapi" = "1.66.0"

[build]
system = "poac"
lib = true
