name: Validate Config

on:
  pull_request:
    paths:
      - '**.toml'

jobs:
  exist:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        key:
          - package.name
          - package.version
          - package.authors
          - package.edition
          - package.repository
          - package.description
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - run: |
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          'test "$(toml get {} ${{ matrix.key }})" != "null"'

  valid_authors:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - run: |
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          'test "$(toml get {} package.authors)" != "[]"'

  valid_edition:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - run: |
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          '[[ "$(toml get {} package.edition)" =~ ^1998|2003|2011|2014|2017|2020$ ]]'

  valid_repository:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - run: |
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          '[[ "$(toml get {} package.repository)" =~ ^\"https:\/\/github\.com\/.*\/tree\/.*\"$ ]]'

  version_eq_filename:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - run: |
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          'test "`echo $(toml get {} package.version) | tr -d '\''\"'\''`.toml" = "$(basename {})"'
        working-directory: manifests

  misleading:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v22.1

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - name: Pick the first change  # FIXME: all changed files
        id: added-package
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "::set-output name=name::$(toml get $file package.name)"
            break
          done

      - name: List package names
        id: existent-packages
        run: |
          LIST=''
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          'LIST="$LIST $(toml get {} package.name)"'
          echo "::set-output name=list::${LIST//${{ steps.added-package.outputs.name }}/}"

      - uses: ken-matsui/misleading-name-check@v1
        id: check-misleading
        with:
          name: ${{ steps.added-package.outputs.name }}
          list: ${{ steps.existent-packages.outputs.list }}

      - name: Test the result
        run: |
          [ '${{ steps.check-misleading.outputs.is-misleading }}' = 'false' ]
