name: Validate Config

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  exists:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        key:
          - package.name
          - package.version
          - package.authors
          - package.edition
          - package.repository
          - package.description
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - run: |
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          'test "$(toml get {} ${{ matrix.key }})" != "null"'

  valid_authors:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - run: |
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          'test "$(toml get {} package.authors)" != "[]"'

  valid_edition:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - run: |
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          '[[ "$(toml get {} package.edition)" =~ ^1998|2003|2011|2014|2017|2020$ ]]'

  version_eq_filename:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli

      - run: |
          find . -name '*.toml' -type f | \
          xargs -I {} bash -c \
          'test "$(echo $(toml get {} package.version) | tr -d '\"').toml" = "$(basename {})"'
